pipeline {
    agent any
    stages {
        
        stage('Staging'){
            steps{
                echo 'Starting staging job'
                build job: 'PIPELINE-FULL-STAGING/develop', parameters: [
                      string(name:'ENVIRONMENT', value: "staging")]
            }
        }
        stage('Merge'){
            steps{
                sh script: """
                    set -x
                    git branch -a
                    git checkout -b develop origin/develop
                    git checkout -b master origin/master
                    git merge develop
                """, label: "Merging code to master"
               sshagent(['jenkinsSSH']) {
                    sh 'touch ~/.ssh/id_rsa'
                    sh 'chmod 600 ~/.ssh/id_rsa'
                    sh 'ssh-add ~/.ssh/id_rsa'
                    sh 'cat ~/.ssh/id_rsa' 
                    sh 'git -i ~/.ssh/id_rsa push origin master'
                }

            }
        }
        stage('Production'){
            steps{
                
                echo 'Starting production job'
                build job: 'PIPELINE-FULL-PRODUCTION/master', parameters: [
                      string(name:'ENVIRONMENT', value: "production")]
            }
        }
    }
    post { 
        always { 
            echo 'Clean env: delete dir'
            cleanWs()
        }
    }
}