pipeline {
    agent any
    stages {
        
        
        stage('SetUp'){
            steps{
                echo 'set url'
                sh "git remote get-url origin | sed 's#https://github.com/##g'"
                sh "git remote set-url origin git@github.com:\$(git remote get-url origin | sed 's#https://github.com/##g')"
            }
        }
        stage('Staging'){
            steps{
                echo 'Starting staging job'
                build job: 'PIPELINE-FULL-STAGING/develop', parameters: [
                      string(name:'ENVIRONMENT', value: "staging")]
            }
        }
        stage('Merge'){
            steps{
                withCredentials([sshUserPrivateKey(credentialsId: 'jenkinsSSH', keyFileVariable: 'SSH_KEY_FILE', usernameVariable: 'SSH_USERNAME')]) {                  
                    
                    git branch -a
                    git checkout -b develop origin/develop
                    git checkout -b master origin/master
                    git merge develop 
                    git '-i ${SSH_KEY_FILE} git push origin master'
                }
                

            }
        }
        stage('Production'){
            steps{
                
                echo 'Starting production job'
                build job: 'PIPELINE-FULL-PRODUCTION/master', parameters: [
                      string(name:'ENVIRONMENT', value: "production")]
            }
        }
    }
    post { 
        always { 
            echo 'Clean env: delete dir'
            cleanWs()
        }
    }
}